name: KillaKreditz
main: com.sleaker.KillaKreditz.KillaKreditz
version: 1.0
author: Sleaker
description: >
             A plugin that awards players with random
             amounts of money for killing creatures.
             supports per world, per creature customizations.