name: CombatEventsLoot
main: com.sleaker.combatevents.loot.CombatEventsLoot
version: 1.0
author: Sleaker
description: >
             A plugin that awards players with random
             amounts of money for killing creatures.
             supports per world, per creature customizations.